# https://github.com/muesli/readme-scribe/
name: readme-scribe
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  markscribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Generate README.md
        uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MARKSCRIBE_TOKEN }}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: "markscribe: update README.md"
